# numpy part 1 


In [ ]:
import numpy as np

In [3]:
l = [1,2,3,4]


In [7]:
ar = np.array(l)

In [8]:
ar

array([1, 2, 3, 4])

In [9]:
type(ar)

numpy.ndarray

In [12]:
np.array([[1,2,3],[1,4,5]])

array([[1, 2, 3],
       [1, 4, 5]])

In [13]:
np.asarray(l)

array([1, 2, 3, 4])

In [15]:
a = [2,3,4] 


In [16]:
np.asarray(a)

array([2, 3, 4])

In [19]:
b = np.matrix(l) ## i will return always two dimensional metrix

In [20]:
b

matrix([[1, 2, 3, 4]])

In [21]:
np.asanyarray(b)  ## it 

matrix([[1, 2, 3, 4]])

In [22]:
a = np.array(l)

In [23]:
a

array([1, 2, 3, 4])

In [24]:
c = a
c

array([1, 2, 3, 4])

In [25]:
a

array([1, 2, 3, 4])

In [26]:
c[0] = 100  ### solo copy
c

array([100,   2,   3,   4])

In [27]:
a

array([100,   2,   3,   4])

In [28]:
d = np.copy(a)  ## deep  copy 

In [29]:
d

array([100,   2,   3,   4])

In [30]:
a[1] =  400
a

array([100, 400,   3,   4])

In [31]:
d

array([100,   2,   3,   4])

In [32]:
np.fromfunction(lambda i,j : i ==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j : i *j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [35]:
np.fromfunction(lambda i,j : i >=j ,(3,3))

array([[ True, False, False],
       [ True,  True, False],
       [ True,  True,  True]])

In [42]:
 iterable  = (i*i for i in range(5))
    

In [43]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [47]:
np.fromstring('234 256',sep = ' ')

array([234., 256.])

In [48]:
np.fromstring('4,5',sep = ',')

array([4., 5.])

In [49]:
### Numpy -- Data types

In [50]:
l = [2,3,4,5,6]

In [51]:
l

[2, 3, 4, 5, 6]

In [52]:
ar = np.array(l)

In [53]:
ar

array([2, 3, 4, 5, 6])

In [54]:
ar.ndim

1

In [55]:
ar2 = np.array([[1,2,4],[1,15,16]])

In [56]:
ar2

array([[ 1,  2,  4],
       [ 1, 15, 16]])

In [57]:
ar2.ndim

2

In [58]:
ar.size


5

In [60]:
ar2.size

6

In [61]:
ar2

array([[ 1,  2,  4],
       [ 1, 15, 16]])

In [62]:
ar2.shape

(2, 3)

In [63]:
ar.shape

(5,)

In [64]:
ar.dtype

dtype('int64')

In [65]:
ar2.dtype

dtype('int64')

In [66]:
ar22 = np.array([(1.4,145,45),(23,45,56)])

In [67]:
ar22

array([[  1.4, 145. ,  45. ],
       [ 23. ,  45. ,  56. ]])

In [68]:
ar22.dtype

dtype('float64')

In [69]:
list(range(5))

[0, 1, 2, 3, 4]

In [70]:
list(range(0.1, 5))

TypeError: 'float' object cannot be interpreted as an integer

In [71]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [73]:
list(np.arange(2.3,5.6,0.4))

[2.3,
 2.6999999999999997,
 3.0999999999999996,
 3.4999999999999996,
 3.8999999999999995,
 4.299999999999999,
 4.699999999999999,
 5.1,
 5.499999999999999]

In [74]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [75]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [77]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [79]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [80]:
ar4 = np.zeros((3,4,2,3))

In [81]:
ar4.ndim

4

In [82]:
np.ones(4)

array([1., 1., 1., 1.])

In [84]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [86]:
on = np.ones((2,3,2))
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [87]:
on +6

array([[[7., 7.],
        [7., 7.],
        [7., 7.]],

       [[7., 7.],
        [7., 7.],
        [7., 7.]]])

In [88]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [90]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [91]:
np.empty((3,5))

array([[4.64344665e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.32404027e-322]])

In [92]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [93]:
np.linspace(2,4,15)

array([2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
       2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
       3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ])

In [94]:
np.logspace(2,5,10)  ## its base is 10

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [95]:
np.logspace(2,5,10,base = 3)  ## its base is 3

array([  9.        ,  12.98024613,  18.72075441,  27.        ,
        38.9407384 ,  56.16226322,  81.        , 116.82221519,
       168.48678967, 243.        ])

In [97]:
arr = np.random.randn(3,4)

In [98]:
import pandas as pd

In [99]:
pd.DataFrame(arr)

0         1         2         3
0  0.604434 -0.072629  3.232680 -0.580015
1  1.627229 -1.392785 -2.980240 -0.941668
2  0.675636  0.092218  1.025185 -0.214725

In [100]:
np.random.randn(3,4)

array([[-0.44867509,  0.16436512,  0.61518711, -0.64426735],
       [ 0.14405371,  0.52356572, -0.03955844, -1.20146117],
       [ 0.14205696, -0.70773295,  1.28416692, -0.19442385]])

In [104]:
np.random.randint(1,110,(3,4))

array([[ 85,  14,  39,  72],
       [  4,  14, 108,  82],
       [ 56,  16,  10,  31]])

In [105]:
np.random.randint(1,110,(300,400))

array([[  7,  67,  73, ...,  93,  78,  44],
       [ 85, 106,  24, ...,  48,  86,  25],
       [ 23,  66,  72, ...,  34,  26,  54],
       ...,
       [ 72,  90, 100, ..., 106,   7,  96],
       [ 66,  58,  72, ...,  58,  76,  67],
       [ 73,  40,   5, ...,  49,  46,  23]])

In [106]:
pd.DataFrame(np.random.randint(1,110,(300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     67    4   82   24   60   64   14   20   92    5  ...   20   54   66   
1     50    8   26   53   12   80   72   42   18   32  ...  101   90   74   
2     13   43   61   85   74   46    9   58   78   68  ...   84    7   64   
3     14  103   58   24    2   20  106   19   40   81  ...   76   95   43   
4     16   10   40   50   98  102   58   72    4   90  ...   27   87   60   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295  103   57   90   11   56   42   39   21   26   20  ...   14   89  104   
296   87   54   64  102  109    7   71   98   86  100  ...   31   26   60   
297   96   93   14   51   70   31   59   31   83   92  ...    4   75   73   
298  100   91    7   21   42   97   68   88    1   44  ...   36   43  108   
299   85   43   39   19   38  107   85   37   15  109  ...   55   93   78   

     393  394  395  396  397  398  399  
0     57  104    4   33    6   84    9  
1     66   51    9    1   49    6   95  
2     69   27   25   12   70   93   31  
3     28  107   74    6    2   18   86  
4     81    2  105   65   80   11   74  
..   ...  ...  ...  ...  ...  ...  ...  
295   23    8   30   78   71   82  101  
296   54   56   93   46    3   48   63  
297   97   46   20   82    5   72   33  
298   95   84   72   98   65   46  107  
299   67   90   14   17   58   23   60  

[300 rows x 400 columns]

In [107]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [108]:
arr = np.random.rand(3,4)

In [109]:
arr

array([[0.67787473, 0.18608734, 0.68613349, 0.4573846 ],
       [0.84812243, 0.74857109, 0.33451749, 0.9427647 ],
       [0.22398617, 0.06515943, 0.27097022, 0.65217814]])

In [111]:
arr.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [112]:
arr.reshape(6,2)

array([[0.67787473, 0.18608734],
       [0.68613349, 0.4573846 ],
       [0.84812243, 0.74857109],
       [0.33451749, 0.9427647 ],
       [0.22398617, 0.06515943],
       [0.27097022, 0.65217814]])

In [114]:
arr1 = arr.reshape(6,-4548486)
arr1

array([[0.67787473, 0.18608734],
       [0.68613349, 0.4573846 ],
       [0.84812243, 0.74857109],
       [0.33451749, 0.9427647 ],
       [0.22398617, 0.06515943],
       [0.27097022, 0.65217814]])

In [115]:
arr1[1]

array([0.68613349, 0.4573846 ])

In [116]:
arr1[1][1]

0.45738460161411976

In [117]:
arr1[2:5]

array([[0.84812243, 0.74857109],
       [0.33451749, 0.9427647 ],
       [0.22398617, 0.06515943]])

In [118]:
arr1[2:5,1]

array([0.74857109, 0.9427647 , 0.06515943])

In [120]:
arr = np.random.randint(1,100,(5,5))
arr

array([[30, 79, 64, 45, 46],
       [98, 56, 79, 11, 71],
       [98, 68, 70, 52, 14],
       [25, 13, 88,  2, 52],
       [56, 71, 85, 49, 96]])

In [122]:
arr[arr>50]

array([79, 64, 98, 56, 79, 71, 98, 68, 70, 52, 88, 52, 56, 71, 85, 96])

In [123]:
arr

array([[30, 79, 64, 45, 46],
       [98, 56, 79, 11, 71],
       [98, 68, 70, 52, 14],
       [25, 13, 88,  2, 52],
       [56, 71, 85, 49, 96]])

In [124]:
arr[2:4,[1,2]]

array([[68, 70],
       [13, 88]])

In [125]:
arr[0][0]

30

In [126]:
arr[0][0] = 500

In [127]:
arr

array([[500,  79,  64,  45,  46],
       [ 98,  56,  79,  11,  71],
       [ 98,  68,  70,  52,  14],
       [ 25,  13,  88,   2,  52],
       [ 56,  71,  85,  49,  96]])

In [4]:
import numpy as np
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [5]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [2, 2, 1]])

In [6]:
arr2

array([[1, 1, 1],
       [2, 1, 2],
       [1, 2, 2]])

In [7]:
arr1+arr2

array([[3, 2, 3],
       [3, 3, 4],
       [3, 4, 3]])

In [8]:
arr1-arr2

array([[ 1,  0,  1],
       [-1,  1,  0],
       [ 1,  0, -1]])

In [9]:
arr1/arr2

array([[2. , 1. , 2. ],
       [0.5, 2. , 1. ],
       [2. , 1. , 0.5]])

In [10]:
arr1*arr2

array([[2, 1, 2],
       [2, 2, 4],
       [2, 4, 2]])

In [13]:
arr1, arr2

(array([[2, 1, 2],
        [1, 2, 2],
        [2, 2, 1]]),
 array([[1, 1, 1],
        [2, 1, 2],
        [1, 2, 2]]))

In [14]:
arr1@arr2

array([[6, 7, 8],
       [7, 7, 9],
       [7, 6, 8]])

In [15]:
arr1/0

/tmp/ipykernel_5669/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [16]:
arr1+100

array([[102, 101, 102],
       [101, 102, 102],
       [102, 102, 101]])

In [17]:
arr1**3

array([[8, 1, 8],
       [1, 8, 8],
       [8, 8, 1]])

## Numpy Broad-casting

In [19]:
arr = np.zeros((4,4))

In [20]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
row = np.array([1,2,3,4])

In [22]:
row

array([1, 2, 3, 4])

In [23]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [24]:
row.T

array([1, 2, 3, 4])

In [25]:
col = np.array([[1,2,3,4]])
col.T

array([[1],
       [2],
       [3],
       [4]])

In [27]:
col.T +arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [28]:
arr1 = np.random.randint(1,4,(3,4))
arr1

array([[1, 2, 2, 1],
       [3, 2, 1, 1],
       [3, 2, 2, 3]])

In [29]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356, 1.        ],
       [1.73205081, 1.41421356, 1.        , 1.        ],
       [1.73205081, 1.41421356, 1.41421356, 1.73205081]])

In [30]:
np.exp(arr1)

array([[ 2.71828183,  7.3890561 ,  7.3890561 ,  2.71828183],
       [20.08553692,  7.3890561 ,  2.71828183,  2.71828183],
       [20.08553692,  7.3890561 ,  7.3890561 , 20.08553692]])

In [31]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.30103   , 0.        ],
       [0.47712125, 0.30103   , 0.        , 0.        ],
       [0.47712125, 0.30103   , 0.30103   , 0.47712125]])

## Numpy part 2 

In [1]:
# Array Manipulation

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[8, 6, 4, 1],
       [7, 9, 9, 4],
       [7, 7, 2, 7]])

In [5]:
arr.reshape(6,2)

array([[8, 6],
       [4, 1],
       [7, 9],
       [9, 4],
       [7, 7],
       [2, 7]])

In [6]:
arr.reshape(2,6)

array([[8, 6, 4, 1, 7, 9],
       [9, 4, 7, 7, 2, 7]])

In [7]:
arr.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [8]:
arr.T

array([[8, 7, 7],
       [6, 9, 7],
       [4, 9, 2],
       [1, 4, 7]])

In [9]:
arr

array([[8, 6, 4, 1],
       [7, 9, 9, 4],
       [7, 7, 2, 7]])

In [10]:
arr.flatten()

array([8, 6, 4, 1, 7, 9, 9, 4, 7, 7, 2, 7])

In [11]:
arr1 = np.array([1,2,4,5,6])

In [12]:
arr1.ndim

1

In [14]:
np.expand_dims(arr1,axis = 1)

array([[1],
       [2],
       [4],
       [5],
       [6]])

In [15]:
np.expand_dims(arr1,axis = 0)

array([[1, 2, 4, 5, 6]])

In [16]:
arr

array([[8, 6, 4, 1],
       [7, 9, 9, 4],
       [7, 7, 2, 7]])

In [17]:
np.squeeze(arr)

array([[8, 6, 4, 1],
       [7, 9, 9, 4],
       [7, 7, 2, 7]])

In [19]:
data = np.array([[1],[2],[3]])

In [20]:
np.squeeze(data)

array([1, 2, 3])

In [21]:
data

array([[1],
       [2],
       [3]])

In [22]:
arr1

array([1, 2, 4, 5, 6])

In [23]:
np.repeat(arr1,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6])

In [24]:
np.roll(arr1,2)

array([5, 6, 1, 2, 4])

In [25]:
arr1

array([1, 2, 4, 5, 6])

In [26]:
np.roll(arr1,3)

array([4, 5, 6, 1, 2])

In [27]:
arr1

array([1, 2, 4, 5, 6])

In [28]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [29]:
## Numpy - Binary Operatipns

In [30]:
arr1 = np.random.randint(1,10,(3,4))

In [34]:
arr2 = np.random.randint(1,10,(3,4))

In [35]:
arr1

array([[3, 7, 8, 1],
       [2, 2, 8, 2],
       [5, 1, 6, 1]])

In [36]:
arr2

array([[5, 9, 6, 9],
       [7, 9, 1, 5],
       [8, 8, 8, 8]])

arr1+arr2

In [37]:
arr1+arr2

array([[ 8, 16, 14, 10],
       [ 9, 11,  9,  7],
       [13,  9, 14,  9]])

In [38]:
arr1*arr2

array([[15, 63, 48,  9],
       [14, 18,  8, 10],
       [40,  8, 48,  8]])

In [39]:
arr1/arr2

array([[0.6       , 0.77777778, 1.33333333, 0.11111111],
       [0.28571429, 0.22222222, 8.        , 0.4       ],
       [0.625     , 0.125     , 0.75      , 0.125     ]])

In [40]:
arr1@arr2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [41]:
arr1-arr2

array([[-2, -2,  2, -8],
       [-5, -7,  7, -3],
       [-3, -7, -2, -7]])

In [42]:
arr1%arr2

array([[3, 7, 2, 1],
       [2, 2, 0, 2],
       [5, 1, 6, 1]])

In [43]:
arr1**arr2

array([[     243, 40353607,   262144,        1],
       [     128,      512,        8,       32],
       [  390625,        1,  1679616,        1]])

In [44]:
arr1 & arr2

array([[1, 1, 0, 1],
       [2, 0, 0, 0],
       [0, 0, 0, 0]])

In [45]:
arr1,arr2

(array([[3, 7, 8, 1],
        [2, 2, 8, 2],
        [5, 1, 6, 1]]),
 array([[5, 9, 6, 9],
        [7, 9, 1, 5],
        [8, 8, 8, 8]]))

In [46]:
~arr1

array([[-4, -8, -9, -2],
       [-3, -3, -9, -3],
       [-6, -2, -7, -2]])

In [47]:
arr1|arr2

array([[ 7, 15, 14,  9],
       [ 7, 11,  9,  7],
       [13,  9, 14,  9]])

In [48]:
arr1>arr2

array([[False, False,  True, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [49]:
## Numpy _string Functions.

In [52]:
arr = np.array(['pradeep','yati'])

In [53]:
arr

array(['pradeep', 'yati'], dtype='<U7')

In [54]:
np.char.upper(arr)

array(['PRADEEP', 'YATI'], dtype='<U7')

In [55]:
np.char.title(arr)

array(['Pradeep', 'Yati'], dtype='<U7')

In [56]:
np.char.capitalize(arr)

array(['Pradeep', 'Yati'], dtype='<U7')

In [57]:
## Numpy Mathematical Functions.

In [58]:
arr1

array([[3, 7, 8, 1],
       [2, 2, 8, 2],
       [5, 1, 6, 1]])

In [59]:
np.sin(arr1)

array([[ 0.14112001,  0.6569866 ,  0.98935825,  0.84147098],
       [ 0.90929743,  0.90929743,  0.98935825,  0.90929743],
       [-0.95892427,  0.84147098, -0.2794155 ,  0.84147098]])

In [60]:
np.cos(arr1)

array([[-0.9899925 ,  0.75390225, -0.14550003,  0.54030231],
       [-0.41614684, -0.41614684, -0.14550003, -0.41614684],
       [ 0.28366219,  0.54030231,  0.96017029,  0.54030231]])

In [61]:
np.tanh(arr1)

array([[0.99505475, 0.99999834, 0.99999977, 0.76159416],
       [0.96402758, 0.96402758, 0.99999977, 0.96402758],
       [0.9999092 , 0.76159416, 0.99998771, 0.76159416]])

In [62]:
np.tan(arr1)

array([[-0.14254654,  0.87144798, -6.79971146,  1.55740772],
       [-2.18503986, -2.18503986, -6.79971146, -2.18503986],
       [-3.38051501,  1.55740772, -0.29100619,  1.55740772]])

In [63]:
np.log10(arr1)

array([[0.47712125, 0.84509804, 0.90308999, 0.        ],
       [0.30103   , 0.30103   , 0.90308999, 0.30103   ],
       [0.69897   , 0.        , 0.77815125, 0.        ]])

In [64]:
np.exp(arr1)

array([[2.00855369e+01, 1.09663316e+03, 2.98095799e+03, 2.71828183e+00],
       [7.38905610e+00, 7.38905610e+00, 2.98095799e+03, 7.38905610e+00],
       [1.48413159e+02, 2.71828183e+00, 4.03428793e+02, 2.71828183e+00]])

In [66]:
np.sqrt((arr1))

array([[1.73205081, 2.64575131, 2.82842712, 1.        ],
       [1.41421356, 1.41421356, 2.82842712, 1.41421356],
       [2.23606798, 1.        , 2.44948974, 1.        ]])

In [67]:
np.power(arr1,3)

array([[ 27, 343, 512,   1],
       [  8,   8, 512,   8],
       [125,   1, 216,   1]])

In [68]:
np.mean(arr1)

3.8333333333333335

In [69]:
np.median(arr1)

2.5

In [73]:
np.mod((arr1))

TypeError: remainder() takes from 2 to 3 positional arguments but 1 were given

In [74]:
np.std(arr1)

2.6718699236468995

In [76]:
np.var(arr1)

7.138888888888888

In [77]:
np.min(arr1)

1

In [78]:
np.max(arr1)

8

In [79]:
## Sort, Search & Counting Functions.

In [80]:
import numpy as np


In [81]:
arr = np.array([4,5,6,8,9,5,2,45,46,65,45,12,32,12])

In [82]:
np.sort(arr)

array([ 2,  4,  5,  5,  6,  8,  9, 12, 12, 32, 45, 45, 46, 65])

In [83]:
np.searchsorted(arr,56)

14

In [84]:
arr1 = np.array([1,0,2,0,3,0,0,0,45,21,0,0,12])

In [85]:
np.count_nonzero(arr1)

6

In [86]:
arr

array([ 4,  5,  6,  8,  9,  5,  2, 45, 46, 65, 45, 12, 32, 12])

In [88]:
np.where(arr>20)

(array([ 7,  8,  9, 10, 12]),)

In [89]:
np.extract(arr>25,arr)

array([45, 46, 65, 45, 32])

In [90]:
## Numpy  -Byte Swapping

In [91]:
arr.byteswap()

array([ 288230376151711744,  360287970189639680,  432345564227567616,
        576460752303423488,  648518346341351424,  360287970189639680,
        144115188075855872, 3242591731706757120, 3314649325744685056,
       4683743612465315840, 3242591731706757120,  864691128455135232,
       2305843009213693952,  864691128455135232])

In [92]:
## copies and views

In [93]:
arr

array([ 4,  5,  6,  8,  9,  5,  2, 45, 46, 65, 45, 12, 32, 12])

In [94]:
a = np.copy(arr)  ## deep copy

In [95]:
b = arr.view() ## solo copy

In [96]:
b

array([ 4,  5,  6,  8,  9,  5,  2, 45, 46, 65, 45, 12, 32, 12])

In [97]:
arr

array([ 4,  5,  6,  8,  9,  5,  2, 45, 46, 65, 45, 12, 32, 12])

In [98]:
b[0] = 101

In [99]:
b

array([101,   5,   6,   8,   9,   5,   2,  45,  46,  65,  45,  12,  32,
        12])

In [100]:
arr

array([101,   5,   6,   8,   9,   5,   2,  45,  46,  65,  45,  12,  32,
        12])

In [101]:
## Numpy  - metrix Library

In [102]:
import numpy.matlib as nm

In [103]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [104]:
nm.ones(4)

matrix([[1., 1., 1., 1.]])

In [105]:
nm.ones((4,5))

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [106]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [107]:
## numpy  - linear algebra

In [108]:
arr1 = np.random.randint([[2,3],[4,5]])

In [109]:
arr2 = np.random.randint([[2,3],[4,5]])

In [110]:
np.dot(arr1,arr2)

array([[1, 5],
       [1, 8]])

In [111]:
arr1@arr2

array([[1, 5],
       [1, 8]])